* enm-test-new-norms.dat
Data for three norms in Pete's paper.
* enm-test-new-norms-2.dat
Data from enm-test after changing ftol_rel to 1e-10 instead of 1e-5. Seems to make no difference. Still using Nelder-Mead.
* enm-test-new-norms-3.dat
Changed to SLSQP with ftol_rel = 1e-10 still. Now the trace distance also has a larger error.
* enm-test-new-norms-3.dat
Changed to SLSQP with ftol_rel = 1e-15. The trace distance still has really high error. I think SLSQP is being weird. It seems like it isn't giving the correct answers
* enm-test-new-optimise.dat
This tests the enm optimiser with the l2 distance instead of the trace distance (as it should be!)
* enm-test-new-optimise-2.dat
Tested SLSQP with the nex l2 distance. The graph is clearly wrong.
* enm-test-new-optimise-ftol=1e-5.dat
Gone back to Nelder-Mead using ftol_rel = 1e-5. 
* enm-test-new-optimise-ftol=1e-6.dat
  Still works.
* enm-test-new-optimise-ftol=1e-8.dat
Still works kind of. There are a few unphysical points
* enm-test-new-optimise-ftol=1e-10.dat
Still works kind of. There are a few unphysical points
* enm-test-new-optimise-ftol=1e-12.dat
Doesn't really work. There are loads of unphysical points.
* enm-test-new-optimise-ftol=1e-14.dat
Definitely terrible.
* enm-test-new-optimise-ftol=1e-5.dat or less
Setting the ftol parameter from 10e-1 and 10e-5: the parameter doesn't make that much difference until you get down to 10e-2 and 1-e-1, where it starts to affect the trace and HS distances (not really the infidelity). By 10e-1 it doesn't really converge.
* enm-test-more-optimise-ftol=1e-5.dat
Now the optimisation works on every purity value, including the ones that are already physical. This should give the same results as above but just takes a bit longer. In reality the middle purity values seem to have more variance. This might be solved by decreasing ftol a bit.
* enm-test-more-optimise-ftol=1e-6.dat
Decreasing ftol does actually reduce the variance in the middle purity values.
* enm-test-more-optimise-ftol=1e-7.dat or more
Improves the variance even more without substantially many unphysical points.
Decreasing ftol further improves the variance at the expense of a few more unphysical points. 
* enm-test-trace1-bobyqa-ftol=1e-6.dat
This test uses the AUGLAG with local optimiser BOBYQA and all ftols set to 1e-6, but with the constrain tol set to 1e-5. It doesn't look right, but it ran fast enough (because I only ran the optimiser for non-physical matrices.)
* enm-test-trace1-bobyqa-2-ftol=1e-6.dat
This uses a new implementation of the fidelity which takes the absolute value of the matrix eigenvalues (assuming they're close to positive.) The graph looks similar to the others.
* enm-test-trace1-bobyqa-2-ftol=1e-4.dat
This is the same as the test above but with a different value for the tolerances (they are all the same).
